### ISSUE TITLE
Download checkpoints with `litgpt serve`

### ISSUE THREAD

**Issue by aniketmaurya** [Lightning-AI/litgpt#1730] opened 2024-09-18 17:37 UTC
### Bug description

Model served using `litgpt serve hf-org/MODEL_ID` doesn't download the weights automatically which is somewhat not intuitive. 

<img width="736" alt="image" src="https://github.com/user-attachments/assets/2ec0040f-60e9-46dd-b590-9fefefdb3e2f">

### What operating system are you using?

Linux

### LitGPT Version

``` 



```

**Comment by rasbt** [comment] 2024-09-18 19:58
Thanks for the note, I am currently at a conf but will take care of that in the next few days

**Comment by merryHunter** [comment] 2024-09-19 02:30
Actually, it's not a bug, seems like the author is referring to serving ANY model, but the litgpt prints in the output an instruction how to do it by setting `repo_id` and `model_name` for any model. Otherwise, for any model that is in the list of models, it will automatically download the weights.
```
root@41f11ab35afa:/app/litgpt# litgpt serve jinaai/reader-lm-0.5b
Unsupported `repo_id`: jinaai/reader-lm-0.5b.
If you are trying to download alternative weights for a supported model, please specify the corresponding model via the `--model_name` option, for example, `litgpt download NousResearch/Hermes-2-Pro-Llama-3-8B --model_name Llama-3-8B`.
Alternatively, please choose a valid `repo_id` from the list of supported models, which can be obtained via `litgpt download list`.
{'accelerator': 'auto',
 'access_token': None,
 'checkpoint_dir': PosixPath('checkpoints/jinaai/reader-lm-0.5b'),
 'devices': 1,
 'max_new_tokens': 50,
 'port': 8000,
 'precision': None,
 'quantize': None,
 'stream': False,
 'temperature': 0.8,
 'top_k': 50,
 'top_p': 1.0}
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
Swagger UI is available at http://0.0.0.0:8000/docs
INFO:     Started server process [26023]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
Initializing model...
Process SpawnProcess-2:
Traceback (most recent call last):
  File "/app/litgpt/litgpt/utils.py", line 601, in auto_download_checkpoint
    check_valid_checkpoint_dir(checkpoint_dir, verbose=False, raise_error=True, ignore_tokenizer_files=ignore_tokenizer_files)
  File "/app/litgpt/litgpt/utils.py", line 127, in check_valid_checkpoint_dir
    raise FileNotFoundError(f"checkpoint_dir {str(checkpoint_dir.absolute())!r}{problem}.")
FileNotFoundError: checkpoint_dir '/app/litgpt/checkpoints/jinaai/reader-lm-0.5b' is not a checkpoint directory.
```

**Comment by rasbt** [comment] 2024-09-19 03:31
I just gave it a try and it works fine for me:

<img width="509" alt="Screenshot 2024-09-18 at 8 29 15 PM" src="https://github.com/user-attachments/assets/2ceacd1f-25c9-4656-871c-b007848001d9">

Thanks to @merryHunter 's comment, I think I now understand what might have happened: My guess is the user tried to download an arbitrary model. Right now, the auto-downloading only works for supported models via `litgpt download list`. Auto-downloading of other models would be out of scope because it would be impossible to support an arbitrary model.

**Closed by rasbt** 2024-09-19 03:31 UTC
Labels: bug

**Comment by merryHunter** [comment] 2024-09-19 03:32
@rasbt sure thing. Have fun at the Pytorch conference! really missing it
