### ISSUE TITLE
Unable to train using LoRA however training with adapter seems fine

### ISSUE THREAD

**Issue by salokr** [Lightning-AI/litgpt#1708] opened 2024-09-03 04:26 UTC
### Bug description

I am trying to fine-tune LLaMA on our college Hopper with 80 GB A100. Whenever I try to fine-tune using LoRA, I get error such as `RuntimeError: GET was unable to find an engine to execute this computation`

I ran using:
> litgpt finetune_lora meta-llama/Llama-2-7b-hf   --data JSON   --data.json_path my_custom_dataset.json   --data.val_split_fraction 0.1   --train.epochs 1   --out_dir out/Llama-2-7b-hf   --precision bf16-true   --devices 1 --train.global_batch_size 1 --train.micro_batch_size 1 --train.max_seq_length 100 
```
Traceback (most recent call last):
  File "/scratch/ssrivas6/envs/litgpt/bin/litgpt", line 8, in <module>
    sys.exit(main())
  File "/scratch/ssrivas6/envs/litgpt/lib/python3.10/site-packages/litgpt/__main__.py", line 71, in main
    CLI(parser_data)
  File "/scratch/ssrivas6/envs/litgpt/lib/python3.10/site-packages/jsonargparse/_cli.py", line 119, in CLI
    return _run_component(component, init.get(subcommand))
  File "/scratch/ssrivas6/envs/litgpt/lib/python3.10/site-packages/jsonargparse/_cli.py", line 204, in _run_component
    return component(**cfg)
  File "/scratch/ssrivas6/envs/litgpt/lib/python3.10/site-packages/litgpt/finetune/lora.py", line 169, in setup
    fabric.launch(main, devices, seed, config, data, checkpoint_dir, out_dir, train, eval, optimizer)
  File "/scratch/ssrivas6/envs/litgpt/lib/python3.10/site-packages/lightning/fabric/fabric.py", line 843, in launch
    return self._wrap_and_launch(function, self, *args, **kwargs)
  File "/scratch/ssrivas6/envs/litgpt/lib/python3.10/site-packages/lightning/fabric/fabric.py", line 929, in _wrap_and_launch
    return to_run(*args, **kwargs)
  File "/scratch/ssrivas6/envs/litgpt/lib/python3.10/site-packages/lightning/fabric/fabric.py", line 934, in _wrap_with_setup
    return to_run(*args, **kwargs)
  File "/scratch/ssrivas6/envs/litgpt/lib/python3.10/site-packages/litgpt/finetune/lora.py", line 218, in main
    fit(
  File "/scratch/ssrivas6/envs/litgpt/lib/python3.10/site-packages/litgpt/finetune/lora.py", line 282, in fit
    validate(fabric, model, val_dataloader, dataclasses.replace(eval, max_iters=2), verbose=False)  # sanity check
  File "/scratch/ssrivas6/envs/litgpt/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/scratch/ssrivas6/envs/litgpt/lib/python3.10/site-packages/litgpt/finetune/lora.py", line 378, in validate
    logits = model(input_ids)
  File "/scratch/ssrivas6/envs/litgpt/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/scratch/ssrivas6/envs/litgpt/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/scratch/ssrivas6/envs/litgpt/lib/python3.10/site-packages/lightning/fabric/wrappers.py", line 141, in forward
    output = self._forward_module(*args, **kwargs)
  File "/scratch/ssrivas6/envs/litgpt/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/scratch/ssrivas6/envs/litgpt/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/scratch/ssrivas6/envs/litgpt/lib/python3.10/site-packages/litgpt/lora.py", line 544, in forward
    x = block(x, cos, sin, mask, input_pos)
  File "/scratch/ssrivas6/envs/litgpt/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/scratch/ssrivas6/envs/litgpt/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/scratch/ssrivas6/envs/litgpt/lib/python3.10/site-packages/litgpt/model.py", line 197, in forward
    attention_output = self.attn(x_normed, cos, sin, mask, input_pos)
  File "/scratch/ssrivas6/envs/litgpt/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/scratch/ssrivas6/envs/litgpt/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/scratch/ssrivas6/envs/litgpt/lib/python3.10/site-packages/litgpt/model.py", line 237, in forward
    qkv = self.attn(x)
  File "/scratch/ssrivas6/envs/litgpt/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/scratch/ssrivas6/envs/litgpt/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/scratch/ssrivas6/envs/litgpt/lib/python3.10/site-packages/litgpt/lora.py", line 425, in forward
    after_B = self.conv1d(
  File "/scratch/ssrivas6/envs/litgpt/lib/python3.10/site-packages/litgpt/lora.py", line 366, in conv1d
    return F.conv1d(input, weight, groups=sum(self.enable_lora))  # (B, C_output, T)
RuntimeError: GET was unable to find an engine to execute this computation
``` 

But if I change from LoRA to adapter tuning, I am able to tune LLaMA as seen below:
> 
```
litgpt finetune_adapter meta-llama/Llama-2-7b-hf   --data JSON   --data.json_path my_custom_dataset.json   --data.val_split_fraction 0.1   --train.epochs 1   --out_dir out/Llama-2-7b-hf   --precision bf16-true   --devices 1 --train.global_batch_size 1 --train.micro_batch_size 1 --train.max_seq_length 100 
```
```
Epoch 1 | iter 1 step 1 | loss train: 2.063, val: n/a | iter time: 1557.97 ms (step)
Epoch 1 | iter 2 step 2 | loss train: 1.684, val: n/a | iter time: 84.60 ms (step)
Epoch 1 | iter 3 step 3 | loss train: 2.040, val: n/a | iter time: 62.15 ms (step)
Epoch 1 | iter 4 step 4 | loss train: 1.941, val: n/a | iter time: 62.24 ms (step)
Epoch 1 | iter 5 step 5 | loss train: 1.974, val: n/a | iter time: 60.35 ms (step)
Epoch 1 | iter 6 step 6 | loss train: 2.007, val: n/a | iter time: 60.33 ms (step)
Epoch 1 | iter 7 step 7 | loss train: 1.760, val: n/a | iter time: 59.91 ms (step)
Epoch 1 | iter 8 ste
```

More details:
> nvidia-smi
```
Tue Sep  3 00:22:34 2024
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 545.23.08              Driver Version: 545.23.08    CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA A100-SXM4-80GB          On  | 00000000:01:00.0 Off |                    0 |
| N/A   43C    P0              94W / 500W |   7262MiB / 81920MiB |    100%	Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA A100-SXM4-80GB          On  | 00000000:41:00.0 Off |                    0 |
| N/A   24C    P0              57W / 500W |	 4MiB / 81920MiB |	0%	Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   2  NVIDIA A100-SXM4-80GB          On  | 00000000:81:00.0 Off |                    0 |
| N/A   25C    P0              58W / 500W |	 4MiB / 81920MiB |	0%	Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   3  NVIDIA A100-SXM4-80GB          On  | 00000000:C1:00.0 Off |                    0 |
| N/A   37C    P0             219W / 500W |  80774MiB / 81920MiB |    100%	Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage	|
|=======================================================================================|
|    0   N/A  N/A    257748	 C   python                                     7974MiB |
|    3   N/A  N/A    231593	 C   python                                    80760MiB |
+---------------------------------------------------------------------------------------+
```

> Output of pip freeze
```
absl-py==2.1.0
accelerate==0.34.0
aiohappyeyeballs==2.4.0
aiohttp==3.10.5
aiosignal==1.3.1
annotated-types==0.7.0
anyio==4.4.0
async-timeout==4.0.3
attrs==24.2.0
bitsandbytes==0.42.0
boto3==1.35.10
botocore==1.35.10
certifi==2024.8.30
chardet==5.2.0
charset-normalizer==3.3.2
click==8.1.7
colorama==0.4.6
DataProperty==1.0.1
datasets==2.21.0
dill==0.3.8
docstring_parser==0.16
evaluate==0.4.2
exceptiongroup==1.2.2
fastapi==0.112.2
filelock==3.13.1
frozenlist==1.4.1
fsspec==2024.2.0
grpcio==1.66.1
h11==0.14.0
httpcore==1.0.5
httpx==0.27.2
huggingface-hub==0.24.6
idna==3.8
importlib_resources==6.4.4
Jinja2==3.1.3
jmespath==1.0.1
joblib==1.4.2
jsonargparse==4.32.1
jsonlines==4.0.0
lightning==2.4.0.dev20240728
lightning-utilities==0.11.7
litdata==0.2.17
litgpt==0.4.11
litserve==0.2.2
lm_eval==0.4.3
lxml==5.3.0
Markdown==3.7
MarkupSafe==2.1.5
mbstrdecoder==1.1.3
more-itertools==10.4.0
mpmath==1.3.0
multidict==6.0.5
multiprocess==0.70.16
networkx==3.2.1
nltk==3.9.1
numexpr==2.10.1
numpy==1.26.3
nvidia-cublas-cu11==11.11.3.6
nvidia-cuda-cupti-cu11==11.8.87
nvidia-cuda-nvrtc-cu11==11.8.89
nvidia-cuda-runtime-cu11==11.8.89
nvidia-cudnn-cu11==8.7.0.84
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.3.0.86
nvidia-cusolver-cu11==11.4.1.48
nvidia-cusparse-cu11==11.7.5.86
nvidia-nccl-cu11==2.20.5
nvidia-nvtx-cu11==11.8.86
packaging==24.1
pandas==2.2.2
pathvalidate==3.2.1
peft==0.12.0
pillow==10.2.0
portalocker==2.10.1
protobuf==5.28.0
psutil==6.0.0
pyarrow==17.0.0
pybind11==2.13.5
pydantic==2.8.2
pydantic_core==2.20.1
pytablewriter==1.2.0
python-dateutil==2.9.0.post0
pytorch-lightning==2.4.0
pytz==2024.1
PyYAML==6.0.2
regex==2024.7.24
requests==2.32.3
rouge_score==0.1.2
s3transfer==0.10.2
sacrebleu==2.4.3
safetensors==0.4.4
scikit-learn==1.5.1
scipy==1.14.1
sentencepiece==0.2.0
six==1.16.0
sniffio==1.3.1
sqlitedict==2.1.0
starlette==0.38.4
sympy==1.12
tabledata==1.3.3
tabulate==0.9.0
tcolorpy==0.1.6
tensorboard==2.17.1
tensorboard-data-server==0.7.2
threadpoolctl==3.5.0
tokenizers==0.19.1
torch==2.3.1+cu118
torchaudio==2.3.1+cu118
torchmetrics==1.4.1
torchvision==0.18.1+cu118
tqdm==4.66.5
tqdm-multiprocess==0.0.11
transformers==4.44.2
triton==2.3.1
typepy==1.3.2
typeshed_client==2.7.0
typing_extensions==4.9.0
tzdata==2024.1
urllib3==2.2.2
uvicorn==0.30.6
Werkzeug==3.0.4
word2number==1.1
xxhash==3.5.0
yarl==1.9.7
zstandard==0.23.0
```
I have kept batch_size and seq_length to 100 to avoid any memory issue

### What operating system are you using?

Linux

### LitGPT Version

``` 
Version: 0.4.11


```

**Comment by Andrei-Aksionov** [comment] 2024-09-03 08:53
Hello @salokr 

That's a weird issue, for sure 🙂.
```python
F.conv1d(input, weight, groups=sum(self.enable_lora))
```

is not a custom operation, should work without any issues whatsoever.

From the pip freeze output (thanks for this, btw) I see some libraries that LitGPT will not try to install. Thus, most likely, you installed LitGPT into an existing venv.
Could you create a new one and install LitGPT into it? Perhaps your current one is corrupted somehow.

**Comment by salokr** [comment] 2024-09-03 17:33
Hi @Andrei-Aksionov,

Thank you for your quick response. 

I created a new environment from scratch using
`python -m venv xyz` and then did `source activate xyz/bin/activate`

To make sure nothing was installed, I once again ran `pip freeze` and saw nothing as an output.

Then I installed litgpt using `pip install litgpt[all]`

and following was the output of `pip freeze`
```
absl-py==2.1.0
accelerate==0.34.0
aiohappyeyeballs==2.4.0
aiohttp==3.10.5
aiosignal==1.3.1
annotated-types==0.7.0
anyio==4.4.0
async-timeout==4.0.3
attrs==24.2.0
bitsandbytes==0.42.0
boto3==1.35.10
botocore==1.35.10
certifi==2024.8.30
chardet==5.2.0
charset-normalizer==3.3.2
click==8.1.7
colorama==0.4.6
DataProperty==1.0.1
datasets==2.21.0
dill==0.3.8
docstring_parser==0.16
evaluate==0.4.2
exceptiongroup==1.2.2
fastapi==0.112.2
filelock==3.15.4
frozenlist==1.4.1
fsspec==2024.6.1
grpcio==1.66.1
h11==0.14.0
httpcore==1.0.5
httpx==0.27.2
huggingface-hub==0.24.6
idna==3.8
importlib_resources==6.4.4
Jinja2==3.1.4
jmespath==1.0.1
joblib==1.4.2
jsonargparse==4.32.1
jsonlines==4.0.0
lightning==2.4.0.dev20240728
lightning-utilities==0.11.7
litdata==0.2.17
litgpt==0.4.11
litserve==0.2.2
lm_eval==0.4.3
lxml==5.3.0
Markdown==3.7
MarkupSafe==2.1.5
mbstrdecoder==1.1.3
more-itertools==10.4.0
mpmath==1.3.0
multidict==6.0.5
multiprocess==0.70.16
networkx==3.3
nltk==3.9.1
numexpr==2.10.1
numpy==2.1.1
nvidia-cublas-cu12==12.1.3.1
nvidia-cuda-cupti-cu12==12.1.105
nvidia-cuda-nvrtc-cu12==12.1.105
nvidia-cuda-runtime-cu12==12.1.105
nvidia-cudnn-cu12==9.1.0.70
nvidia-cufft-cu12==11.0.2.54
nvidia-curand-cu12==10.3.2.106
nvidia-cusolver-cu12==11.4.5.107
nvidia-cusparse-cu12==12.1.0.106
nvidia-nccl-cu12==2.20.5
nvidia-nvjitlink-cu12==12.6.68
nvidia-nvtx-cu12==12.1.105
packaging==24.1
pandas==2.2.2
pathvalidate==3.2.1
peft==0.12.0
portalocker==2.10.1
protobuf==5.28.0
psutil==6.0.0
pyarrow==17.0.0
pybind11==2.13.5
pydantic==2.8.2
pydantic_core==2.20.1
pytablewriter==1.2.0
python-dateutil==2.9.0.post0
pytorch-lightning==2.4.0
pytz==2024.1
PyYAML==6.0.2
regex==2024.7.24
requests==2.32.3
rouge_score==0.1.2
s3transfer==0.10.2
sacrebleu==2.4.3
safetensors==0.4.4
scikit-learn==1.5.1
scipy==1.14.1
sentencepiece==0.2.0
six==1.16.0
sniffio==1.3.1
sqlitedict==2.1.0
starlette==0.38.4
sympy==1.13.2
tabledata==1.3.3
tabulate==0.9.0
tcolorpy==0.1.6
tensorboard==2.17.1
tensorboard-data-server==0.7.2
threadpoolctl==3.5.0
tokenizers==0.19.1
torch==2.4.0
torchmetrics==1.4.1
tqdm==4.66.5
tqdm-multiprocess==0.0.11
transformers==4.44.2
triton==3.0.0
typepy==1.3.2
typeshed_client==2.7.0
typing_extensions==4.12.2
tzdata==2024.1
urllib3==2.2.2
uvicorn==0.30.6
Werkzeug==3.0.4
word2number==1.1
xxhash==3.5.0
yarl==1.9.7
zstandard==0.23.0
```
Then once again I did: `litgpt finetune_lora meta-llama/Llama-2-7b-hf --data JSON --data.json_path my_custom_dataset.json --data.val_split_fraction 0.1 --train.epochs 1 --out_dir out/Llama-2-7b-hf --precision bf16-true --devices 1 --train.global_batch_size 1 --train.micro_batch_size 1 --train.max_seq_length 100`

but I got a separate issue this time:
```
WARNING:

You should always run with libnvidia-ml.so that is installed with your
NVIDIA Display Driver. By default it's installed in /usr/lib and /usr/lib64.
libnvidia-ml.so in GDK package is a stub library that is attached only for
build purposes (e.g. machine that you build your application doesn't have
to have Display Driver installed).
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
WARNING:

You should always run with libnvidia-ml.so that is installed with your
NVIDIA Display Driver. By default it's installed in /usr/lib and /usr/lib64.
libnvidia-ml.so in GDK package is a stub library that is attached only for
build purposes (e.g. machine that you build your application doesn't have
to have Display Driver installed).
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
WARNING:

You should always run with libnvidia-ml.so that is installed with your
NVIDIA Display Driver. By default it's installed in /usr/lib and /usr/lib64.
libnvidia-ml.so in GDK package is a stub library that is attached only for
build purposes (e.g. machine that you build your application doesn't have
to have Display Driver installed).
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Seed set to 1337
Traceback (most recent call last):
  File "/scratch/ssrivas6/envs/xyz/bin/litgpt", line 8, in <module>
    sys.exit(main())
  File "/scratch/ssrivas6/envs/xyz/lib/python3.10/site-packages/litgpt/__main__.py", line 71, in main
    CLI(parser_data)
  File "/scratch/ssrivas6/envs/xyz/lib/python3.10/site-packages/jsonargparse/_cli.py", line 119, in CLI
    return _run_component(component, init.get(subcommand))
  File "/scratch/ssrivas6/envs/xyz/lib/python3.10/site-packages/jsonargparse/_cli.py", line 204, in _run_component
    return component(**cfg)
  File "/scratch/ssrivas6/envs/xyz/lib/python3.10/site-packages/litgpt/finetune/lora.py", line 169, in setup
    fabric.launch(main, devices, seed, config, data, checkpoint_dir, out_dir, train, eval, optimizer)
  File "/scratch/ssrivas6/envs/xyz/lib/python3.10/site-packages/lightning/fabric/fabric.py", line 843, in launch
    return self._wrap_and_launch(function, self, *args, **kwargs)
  File "/scratch/ssrivas6/envs/xyz/lib/python3.10/site-packages/lightning/fabric/fabric.py", line 929, in _wrap_and_launch
    return to_run(*args, **kwargs)
  File "/scratch/ssrivas6/envs/xyz/lib/python3.10/site-packages/lightning/fabric/fabric.py", line 934, in _wrap_with_setup
    return to_run(*args, **kwargs)
  File "/scratch/ssrivas6/envs/xyz/lib/python3.10/site-packages/litgpt/finetune/lora.py", line 198, in main
    model = GPT(config)
  File "/scratch/ssrivas6/envs/xyz/lib/python3.10/site-packages/litgpt/lora.py", line 515, in __init__
    h=nn.ModuleList(Block(config, block_idx) for block_idx in range(config.n_layer)),
  File "/scratch/ssrivas6/envs/xyz/lib/python3.10/site-packages/torch/nn/modules/container.py", line 281, in __init__
    self += modules
  File "/scratch/ssrivas6/envs/xyz/lib/python3.10/site-packages/torch/nn/modules/container.py", line 322, in __iadd__
    return self.extend(modules)
  File "/scratch/ssrivas6/envs/xyz/lib/python3.10/site-packages/torch/nn/modules/container.py", line 403, in extend
    for i, module in enumerate(modules):
  File "/scratch/ssrivas6/envs/xyz/lib/python3.10/site-packages/litgpt/lora.py", line 515, in <genexpr>
    h=nn.ModuleList(Block(config, block_idx) for block_idx in range(config.n_layer)),
  File "/scratch/ssrivas6/envs/xyz/lib/python3.10/site-packages/litgpt/lora.py", line 580, in __init__
    self.attn = CausalSelfAttention(config, block_idx)
  File "/scratch/ssrivas6/envs/xyz/lib/python3.10/site-packages/litgpt/lora.py", line 600, in __init__
    self.attn = LoRAQKVLinear(
  File "/scratch/ssrivas6/envs/xyz/lib/python3.10/site-packages/litgpt/lora.py", line 217, in __init__
    self.linear = torch.nn.Linear(in_features, out_features, **kwargs)
  File "/scratch/ssrivas6/envs/xyz/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 99, in __init__
    self.weight = Parameter(torch.empty((out_features, in_features), **factory_kwargs))
  File "/scratch/ssrivas6/envs/xyz/lib/python3.10/site-packages/lightning/fabric/utilities/init.py", line 53, in __torch_function__
    return func(*args, **kwargs)
  File "/scratch/ssrivas6/envs/xyz/lib/python3.10/site-packages/torch/utils/_device.py", line 79, in __torch_function__
    return func(*args, **kwargs)
RuntimeError: r.nvmlDeviceGetNvLinkRemoteDeviceType_ INTERNAL ASSERT FAILED at "../c10/cuda/driver_api.cpp":27, please report a bug to PyTorch. Can't find nvmlDeviceGetNvLinkRemoteDeviceType: /opt/sw/spack/apps/linux-centos8-cascadelake/gcc-9.3.0/cuda-11.2.1-h3/lib64/libnvidia-ml.so.1: undefined symbol: nvmlDeviceGetNvLinkRemoteDeviceType

```

Here's the output of `LD_LIBRARY_PATH` for more reference:
```
/opt/sw/other/apps/cudnn/cudnn-linux-x86_64-8.9.7.29_cuda12-archive/lib:/opt/sw/other/apps/cuda/12.3.1/lib64:/usr/local/cuda-11.2/lib64:/opt/sw/spack/apps/linux-centos8-cascadelake/gcc-9.3.0/cuda-11.2.1-h3/lib64:/opt/sw/spack/apps/linux-centos8-cascadelake/gcc-9.3.0/zlib-1.2.11-e3/lib:/opt/sw/spack/apps/linux-centos8-cascadelake/gcc-9.3.0/libiconv-1.16-y3/lib:/opt/sw/other/apps/cudnn/cudnn-linux-x86_64-8.9.7.29_cuda12-archive/lib:/opt/sw/other/apps/cuda/12.3.1/lib64:/usr/local/cuda-11.2/lib64:/opt/ohpc/pub/libs/hwloc/2.1.0/lib:/opt/ohpc/pub/mpi/libfabric/1.10.1/lib:/opt/sw/spack/apps/linux-rhel8-x86_64_v2/gcc-9.3.0/ucx-1.12.1-4g/lib:/opt/ohpc/pub/mpi/openmpi4-gnu9/4.0.4/lib:/opt/ohpc/pub/compiler/gcc/9.3.0/lib64
```

**Comment by Andrei-Aksionov** [comment] 2024-09-04 11:53
Hey @salokr 
Thanks for the detailed answer.

It looks like something is messed up with drivers/CUDA.
And for some reason it's triggered by `conv1d` operator.

To verify that it's indeed a case, could you run this code snippet:
```python
import torch

input = torch.rand((2, 16, 4))
weight = torch.rand((16, 8, 1))
groups = 2

torch.nn.functional.conv1d(input, weight, groups=groups)
```

If it doesn't work, then the problem is on your side.

If not, well, we can continue investigating 🙂.

**Comment by salokr** [comment] 2024-09-04 16:27
Hi,

Thank you for getting back.

I resolved the issue.

I was looking to resolve this warning:
```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
WARNING:

You should always run with libnvidia-ml.so that is installed with your
NVIDIA Display Driver. By default it's installed in /usr/lib and /usr/lib64.
libnvidia-ml.so in GDK package is a stub library that is attached only for
build purposes (e.g. machine that you build your application doesn't have
to have Display Driver installed).
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
/scratch/ssrivas6/envs/xyz/lib/python3.10/site-packages/torch/cuda/__init__.py:654: UserWarning: Can't initialize NVML
  warnings.warn("Can't initialize NVML")
```
and after searching for this warning, I got to know that my LD_LIBRARY_PATH is incorrectly set.

I changed it to:
```
export PATH=$HOME/local/cuda/bin:$PATH
export LD_LIBRARY_PATH=$HOME/local/cuda/lib64:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/usr/lib64:$LD_LIBRARY_PATH
```

and I can see the training process going on now.

Thank you :)

**Comment by Andrei-Aksionov** [comment] 2024-09-04 16:32
Glad that it was resolved.
I'm closing the issue.

**Closed by Andrei-Aksionov** 2024-09-04 16:32 UTC
Labels: bug
