### ISSUE TITLE
Using litgpt.generate.tp for multi-GPU inference is nearly 2 times slower than single-GPU inference with litgpt.generate.base

### ISSUE THREAD

**Issue by kstanghere** [Lightning-AI/litgpt#1580] opened 2024-07-13 05:57 UTC
While conducting inference on 1000 data samples using phi-mini-4k, I discovered that using litgpt.generate.tp for 2-GPU inference is nearly 2 times slower than single-GPU inference with litgpt.generate.base. This communication latency seems excessively high.

**Comment by rasbt** [comment] 2024-07-13 11:49
Thanks for opening! I am closing because it seems like a duplicate of #1581  but let's continue the discussion there.

**Closed by rasbt** 2024-07-13 11:49 UTC
Labels: question
