### ISSUE TITLE
Segmentation fault (core dumped) when 'import lit_gpt'

### ISSUE THREAD

**Issue by ZhouqyCH** [Lightning-AI/litgpt#910] opened 2024-01-31 03:38 UTC
version info:
jsonargparse             4.27.2
jsonlines                4.0.0
lightning                2.1.2
lightning-cloud          0.5.52
lightning-utilities      0.10.1
torch                    2.1.2+cu118

When 'import lib_gpt', an error is thrown 'Segmentation fault (core dumped)' without any extra explaination.

**Comment by carmocca** [comment] 2024-01-31 18:11
Are you able to import torch?

`python -c "import torch"`

This cannot be caused by lit-gpt itself, must be a dependency segfaulting.

You can also try creating an new virtual environment

**Comment by rasbt** [comment] 2024-03-29 18:02
Closing because this was hopefully resolved. But please feel free to reopen if the issue persists.

**Closed by rasbt** 2024-03-29 18:02 UTC
Labels: question
