### ISSUE TITLE
LitGPT Python API seems to use more memory than `chat`

### ISSUE THREAD

**Issue by rasbt** [Lightning-AI/litgpt#1588] opened 2024-07-16 21:15 UTC
### Bug description

To reproduce:

```
from litgpt import LLM

llm = LLM.load("mistralai/mathstral-7B-v0.1")
```

or even 

```
from litgpt import LLM

llm = LLM.load("mistralai/mathstral-7B-v0.1", quantize="bnb.nf4")
```

results in an out-of-memory error on an A10G with 23 GB memory.

It works fine via 

```
litgpt chat mistralai/mathstral-7B-v0.1
```

### What operating system are you using?

Unknown

### LitGPT Version

0.4.4

**Comment by Andrei-Aksionov** [comment] 2024-07-17 12:02
I think it's a duplicate of #1582

**Comment by rasbt** [comment] 2024-07-17 12:08
Thanks! I have a bunch of morning meetings but plan to take care of it today

**Closed** 2024-07-17 18:50 UTC
Labels: bug
